name: Docker Image CI

on:
  push:
    branches: ["main", "genevera/de-cuda"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GH container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/${{github.actor}}/video-sampler:latest
          ghcr.io/${{github.actor}}/video-sampler:${{github.sha}}
